version: "3.8"

services:
  backend:
    image: backend:staging
    container_name: devlearn-backend
    ports:
      - "8080:8080"

  frontend:
    image: frontend:staging
    container_name: devlearn-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
